/**
 * PM2 Ecosystem Configuration
 * 
 * This file is used for deploying backend applications generated by Config Generator.
 * Place this file in your backend project root directory.
 * 
 * Usage:
 *   pm2 start ecosystem.config.js --env production
 *   pm2 save
 *   pm2 startup
 */

module.exports = {
  apps: [
    {
      name: 'api',
      script: './server.js', // or './src/index.js' depending on your setup
      instances: 1,
      exec_mode: 'fork', // Use 'fork' for single instance
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5000,
      },
      // Logging
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      
      // Process management
      autorestart: true,
      max_memory_restart: '500M',
      watch: false, // Set to true in development only
      
      // Advanced features
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],

  /**
   * Deployment configuration (optional)
   * Uncomment and configure if using PM2 deploy feature
   */
  // deploy: {
  //   production: {
  //     user: 'root',
  //     host: 'api.shipforge.dev',
  //     ref: 'origin/main',
  //     repo: 'git@github.com:yourusername/your-backend.git',
  //     path: '/var/www/production',
  //     'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env production',
  //   },
  // },
};
